export const routes = {
  home: '/',
  warband: '/warband',
  game: '/game',
  singleGame: '/game/single',
  campaignGame: '/game/campaign',
  campaign: '/campaign',
  map: '/map',
  multiplayer: '/multiplayer',
  tournaments: '/tournaments',
  packs: '/packs',
  collection: '/collection',
  trading: '/trading',
  treasury: '/treasury',
  ladder: '/ladder',
  history: '/history',
  settings: '/settings',
  wallet: '/wallet',
  marketplace: '/marketplace',
  explorer: '/explorer',
  admin: '/admin',
  runeTestnetPrototype: '/testnet/rune',
};
