export const routes = {
  home: '/',
  warband: '/warband',
  game: '/game',
  campaign: '/campaign',
  multiplayer: '/multiplayer',
  tournaments: '/tournaments',
  packs: '/packs',
  collection: '/collection',
  trading: '/trading',
  treasury: '/treasury',
  ladder: '/ladder',
  history: '/history',
  settings: '/settings',
  marketplace: '/marketplace',
  explorer: '/explorer',
  admin: '/admin',
};
