/**
 * Frame PNG path resolver.
 *
 * PNGs are generated by `scripts/exportCardFrames.ts` and live at
 * `client/public/art/frames/{rarity}/{element}.png`. This module is
 * the runtime-side mirror of that file layout — single source of
 * truth on the runtime side, matching `assetPathFor` for NFTs.
 *
 * Invariant: `framePathFor(rarity, element)` returns a path that
 * must exist (the export script writes all 32 combinations at build
 * time). If the file is missing, `<FrameStatic>` falls back to the
 * SVG-only direction so the lab never breaks.
 */

import type { Rarity } from '@shared/schemas/rarity';
import type { NorseElement } from '../../types/NorseTypes';

const FRAME_DIR = '/art/frames';
const FRAME_EXT = '.png';

export function framePathFor(rarity: Rarity, element: NorseElement): string {
	return `${FRAME_DIR}/${rarity}/${element}${FRAME_EXT}`;
}
