# syntax=docker/dockerfile:1.7

ARG NODE_VERSION=20.20.2
ARG NODE_ALPINE_VERSION=3.22

FROM node:${NODE_VERSION}-alpine${NODE_ALPINE_VERSION} AS deps
WORKDIR /app

ENV NPM_CONFIG_FETCH_RETRIES=5
ENV NPM_CONFIG_FETCH_RETRY_MINTIMEOUT=20000
ENV NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT=120000

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN --mount=type=cache,target=/root/.local/share/pnpm/store \
    corepack enable \
    && pnpm install --frozen-lockfile --no-audit

FROM deps AS build
WORKDIR /app

ARG VITE_NETWORK_STAGE=testnet
ARG VITE_RAGNAROK_PROTOCOL_ID=rk_game_testnet
ARG VITE_RAGNAROK_COLLECTION_ID=ragnarok-testnet
ARG VITE_RAGNAROK_RESET_EPOCH=alfa-testnet-full-nft-2026-05-22
ARG VITE_RAGNAROK_ADMIN_ACCOUNT=ragnarok-test
ARG VITE_RAGNAROK_ADMIN_OPERATOR_ACCOUNT=ragnarok-test-operator
ARG VITE_RAGNAROK_GENESIS_ACCOUNT=ragnarok-test
ARG VITE_RAGNAROK_TREASURY_ACCOUNT=ragp2p
ARG VITE_RAGNAROK_INDEX_ACCOUNT=ragp2p
ARG VITE_RAGNAROK_INDEXER_URL
ARG VITE_RAGNAROK_ART_INDEXER_URL
ARG VITE_NFTLOX_PROTOCOL_ID
ARG VITE_NFT_ART_BASE_URL
ARG VITE_EXTERNAL_URL_BASE
ARG VITE_SEASON_START=2026-06-14T23:28:54Z
ARG VITE_RAGNAROK_INDEX_START_BLOCK=109016418

ENV VITE_NETWORK_STAGE=$VITE_NETWORK_STAGE
ENV VITE_RAGNAROK_PROTOCOL_ID=$VITE_RAGNAROK_PROTOCOL_ID
ENV VITE_RAGNAROK_COLLECTION_ID=$VITE_RAGNAROK_COLLECTION_ID
ENV VITE_RAGNAROK_RESET_EPOCH=$VITE_RAGNAROK_RESET_EPOCH
ENV VITE_RAGNAROK_ADMIN_ACCOUNT=$VITE_RAGNAROK_ADMIN_ACCOUNT
ENV VITE_RAGNAROK_ADMIN_OPERATOR_ACCOUNT=$VITE_RAGNAROK_ADMIN_OPERATOR_ACCOUNT
ENV VITE_RAGNAROK_GENESIS_ACCOUNT=$VITE_RAGNAROK_GENESIS_ACCOUNT
ENV VITE_RAGNAROK_TREASURY_ACCOUNT=$VITE_RAGNAROK_TREASURY_ACCOUNT
ENV VITE_RAGNAROK_INDEX_ACCOUNT=$VITE_RAGNAROK_INDEX_ACCOUNT
ENV VITE_RAGNAROK_INDEXER_URL=$VITE_RAGNAROK_INDEXER_URL
ENV VITE_RAGNAROK_ART_INDEXER_URL=$VITE_RAGNAROK_ART_INDEXER_URL
ENV VITE_NFTLOX_PROTOCOL_ID=$VITE_NFTLOX_PROTOCOL_ID
ENV VITE_NFT_ART_BASE_URL=$VITE_NFT_ART_BASE_URL
ENV VITE_EXTERNAL_URL_BASE=$VITE_EXTERNAL_URL_BASE
ENV VITE_SEASON_START=$VITE_SEASON_START
ENV VITE_RAGNAROK_INDEX_START_BLOCK=$VITE_RAGNAROK_INDEX_START_BLOCK

COPY . .
RUN pnpm run verify:runtime-env -- --mode=alfa-testnet && pnpm run build:alfa-testnet

FROM deps AS prod-deps
WORKDIR /app
RUN pnpm install --prod --frozen-lockfile && pnpm store prune

FROM node:${NODE_VERSION}-alpine${NODE_ALPINE_VERSION} AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=5000
ENV VITE_NETWORK_STAGE=testnet
ENV VITE_RAGNAROK_PROTOCOL_ID=rk_game_testnet
ENV VITE_RAGNAROK_COLLECTION_ID=ragnarok-testnet
ENV VITE_RAGNAROK_RESET_EPOCH=alfa-testnet-full-nft-2026-05-22
ENV VITE_RAGNAROK_ADMIN_ACCOUNT=ragnarok-test
ENV VITE_RAGNAROK_ADMIN_OPERATOR_ACCOUNT=ragnarok-test-operator
ENV VITE_RAGNAROK_GENESIS_ACCOUNT=ragnarok-test
ENV VITE_RAGNAROK_TREASURY_ACCOUNT=ragp2p
ENV VITE_RAGNAROK_INDEX_ACCOUNT=ragp2p
ENV RAGNAROK_PROTOCOL_ID=rk_game_testnet
ENV RAGNAROK_RESET_EPOCH=alfa-testnet-full-nft-2026-05-22
ENV RAGNAROK_ADMIN_OPERATOR_ACCOUNT=ragnarok-test-operator
ENV RAGNAROK_CHAIN_STATE_FILE=data/chain-state.alfa-testnet.json
ENV RAGNAROK_NFT_OWNERSHIP_SOURCE=json
ENV RAGNAROK_SEASON_START=2026-06-14T23:28:54Z
ENV RAGNAROK_INDEX_START_BLOCK=109016418

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY --from=prod-deps /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules/esbuild ./node_modules/esbuild
COPY --from=build /app/node_modules/@esbuild ./node_modules/@esbuild
COPY --from=build /app/scripts/verifyRuntimeEnv.mjs ./scripts/verifyRuntimeEnv.mjs

EXPOSE 5000

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:' + (process.env.PORT || 5000) + '/api/health').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))"

CMD ["sh", "-c", "node scripts/verifyRuntimeEnv.mjs --mode ${RAGNAROK_RUNTIME_MODE:-alfa-testnet} --scope runtime && node dist/index.js --mode ${RAGNAROK_RUNTIME_MODE:-alfa-testnet}"]
