# syntax=docker/dockerfile:1.7

ARG NODE_VERSION=24.19.0
ARG NODE_ALPINE_VERSION=3.24

FROM node:${NODE_VERSION}-alpine${NODE_ALPINE_VERSION} AS deps
WORKDIR /app

ENV NPM_CONFIG_FETCH_RETRIES=5
ENV NPM_CONFIG_FETCH_RETRY_MINTIMEOUT=20000
ENV NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT=120000

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
RUN --mount=type=cache,target=/root/.local/share/pnpm/store \
    corepack enable \
    && printf 'node-linker=hoisted\n' >> .npmrc \
    && pnpm install --frozen-lockfile

FROM deps AS build
WORKDIR /app

# Public Alfa fingerprint. Redeclare the same ARG defaults in the runner
# stage so a --build-arg cannot bake one epoch into JS and another into Node.
# Rotating VITE_RAGNAROK_RESET_EPOCH is a wipe, not a routine rebuild.
ARG VITE_NETWORK_STAGE=testnet
ARG VITE_RAGNAROK_PROTOCOL_ID=rk_game_testnet
ARG VITE_RAGNAROK_COLLECTION_ID=ragnarok-testnet
ARG VITE_RAGNAROK_RESET_EPOCH=alfa-testnet-full-nft-2026-05-22
ARG VITE_RAGNAROK_ADMIN_ACCOUNT=ragnaroktestnet
ARG VITE_RAGNAROK_ADMIN_OPERATOR_ACCOUNT=ragp2p
ARG VITE_RAGNAROK_GENESIS_ACCOUNT=ragnaroktestnet
ARG VITE_RAGNAROK_TREASURY_ACCOUNT=ragp2p
ARG VITE_RAGNAROK_INDEX_ACCOUNT=ragp2p
ARG VITE_RAGNAROK_INDEXER_URL
ARG VITE_RAGNAROK_ART_INDEXER_URL
ARG VITE_NFT_ART_BASE_URL=https://dhenz14.github.io/norse-mythos-card-game
ARG VITE_EXTERNAL_URL_BASE=https://testnetdev.ragnaroknft.quest
ARG VITE_SEASON_START=2026-06-14T23:28:54Z
ARG VITE_RAGNAROK_INDEX_START_BLOCK=109016418

ENV VITE_NETWORK_STAGE=$VITE_NETWORK_STAGE
ENV VITE_RAGNAROK_PROTOCOL_ID=$VITE_RAGNAROK_PROTOCOL_ID
ENV VITE_RAGNAROK_COLLECTION_ID=$VITE_RAGNAROK_COLLECTION_ID
ENV VITE_RAGNAROK_RESET_EPOCH=$VITE_RAGNAROK_RESET_EPOCH
ENV VITE_RAGNAROK_ADMIN_ACCOUNT=$VITE_RAGNAROK_ADMIN_ACCOUNT
ENV VITE_RAGNAROK_ADMIN_OPERATOR_ACCOUNT=$VITE_RAGNAROK_ADMIN_OPERATOR_ACCOUNT
ENV VITE_RAGNAROK_GENESIS_ACCOUNT=$VITE_RAGNAROK_GENESIS_ACCOUNT
ENV VITE_RAGNAROK_TREASURY_ACCOUNT=$VITE_RAGNAROK_TREASURY_ACCOUNT
ENV VITE_RAGNAROK_INDEX_ACCOUNT=$VITE_RAGNAROK_INDEX_ACCOUNT
ENV VITE_RAGNAROK_INDEXER_URL=$VITE_RAGNAROK_INDEXER_URL
ENV VITE_RAGNAROK_ART_INDEXER_URL=$VITE_RAGNAROK_ART_INDEXER_URL
ENV VITE_NFT_ART_BASE_URL=$VITE_NFT_ART_BASE_URL
ENV VITE_EXTERNAL_URL_BASE=$VITE_EXTERNAL_URL_BASE
ENV VITE_SEASON_START=$VITE_SEASON_START
ENV VITE_RAGNAROK_INDEX_START_BLOCK=$VITE_RAGNAROK_INDEX_START_BLOCK
ENV RAGNAROK_PROTOCOL_ID=$VITE_RAGNAROK_PROTOCOL_ID
ENV RAGNAROK_RESET_EPOCH=$VITE_RAGNAROK_RESET_EPOCH
ENV RAGNAROK_SEASON_START=$VITE_SEASON_START
ENV RAGNAROK_INDEX_START_BLOCK=$VITE_RAGNAROK_INDEX_START_BLOCK

COPY . .
RUN pnpm run verify:runtime-env -- --mode=alfa-testnet && pnpm run build:alfa-testnet \
	&& mkdir -p /opt/runtime-esbuild \
	&& cp -a node_modules/esbuild /opt/runtime-esbuild/esbuild \
	&& if [ -d node_modules/@esbuild ]; then cp -a node_modules/@esbuild /opt/runtime-esbuild/@esbuild; fi

FROM deps AS prod-deps
WORKDIR /app
RUN pnpm install --prod --frozen-lockfile && pnpm store prune

FROM node:${NODE_VERSION}-alpine${NODE_ALPINE_VERSION} AS runner
WORKDIR /app
ARG VITE_NETWORK_STAGE=testnet
ARG VITE_RAGNAROK_PROTOCOL_ID=rk_game_testnet
ARG VITE_RAGNAROK_COLLECTION_ID=ragnarok-testnet
ARG VITE_RAGNAROK_RESET_EPOCH=alfa-testnet-full-nft-2026-05-22
ARG VITE_RAGNAROK_ADMIN_ACCOUNT=ragnaroktestnet
ARG VITE_RAGNAROK_ADMIN_OPERATOR_ACCOUNT=ragp2p
ARG VITE_RAGNAROK_GENESIS_ACCOUNT=ragnaroktestnet
ARG VITE_RAGNAROK_TREASURY_ACCOUNT=ragp2p
ARG VITE_RAGNAROK_INDEX_ACCOUNT=ragp2p
ARG VITE_NFT_ART_BASE_URL=https://dhenz14.github.io/norse-mythos-card-game
ARG VITE_EXTERNAL_URL_BASE=https://testnetdev.ragnaroknft.quest
ARG VITE_SEASON_START=2026-06-14T23:28:54Z
ARG VITE_RAGNAROK_INDEX_START_BLOCK=109016418
ENV NODE_ENV=production
ENV PORT=5000
ENV RAGNAROK_RUNTIME_MODE=alfa-testnet
ENV VITE_NETWORK_STAGE=$VITE_NETWORK_STAGE
ENV VITE_RAGNAROK_PROTOCOL_ID=$VITE_RAGNAROK_PROTOCOL_ID
ENV VITE_RAGNAROK_COLLECTION_ID=$VITE_RAGNAROK_COLLECTION_ID
ENV VITE_RAGNAROK_RESET_EPOCH=$VITE_RAGNAROK_RESET_EPOCH
ENV VITE_RAGNAROK_ADMIN_ACCOUNT=$VITE_RAGNAROK_ADMIN_ACCOUNT
ENV VITE_RAGNAROK_ADMIN_OPERATOR_ACCOUNT=$VITE_RAGNAROK_ADMIN_OPERATOR_ACCOUNT
ENV VITE_RAGNAROK_GENESIS_ACCOUNT=$VITE_RAGNAROK_GENESIS_ACCOUNT
ENV VITE_RAGNAROK_TREASURY_ACCOUNT=$VITE_RAGNAROK_TREASURY_ACCOUNT
ENV VITE_RAGNAROK_INDEX_ACCOUNT=$VITE_RAGNAROK_INDEX_ACCOUNT
ENV VITE_NFT_ART_BASE_URL=$VITE_NFT_ART_BASE_URL
ENV VITE_EXTERNAL_URL_BASE=$VITE_EXTERNAL_URL_BASE
ENV VITE_SEASON_START=$VITE_SEASON_START
ENV VITE_RAGNAROK_INDEX_START_BLOCK=$VITE_RAGNAROK_INDEX_START_BLOCK
ENV RAGNAROK_PROTOCOL_ID=$VITE_RAGNAROK_PROTOCOL_ID
ENV RAGNAROK_RESET_EPOCH=$VITE_RAGNAROK_RESET_EPOCH
ENV RAGNAROK_ADMIN_OPERATOR_ACCOUNT=$VITE_RAGNAROK_ADMIN_OPERATOR_ACCOUNT
ENV RAGNAROK_SEASON_START=$VITE_SEASON_START
ENV RAGNAROK_INDEX_START_BLOCK=$VITE_RAGNAROK_INDEX_START_BLOCK
ENV RAGNAROK_CHAIN_STATE_FILE=data/chain-state.alfa-testnet.json
ENV RAGNAROK_NFT_OWNERSHIP_SOURCE=json
ENV ENABLE_CHAIN_INDEXER=true
ENV RAGNAROK_RANGE_SCAN=true
ENV RAGNAROK_HAF_ENDPOINTS=https://api.hive.blog
ENV ENABLE_INDEX_CHECKPOINT_PUBLISHER=false
ENV RAGNAROK_INDEX_CHECKPOINT_DRY_RUN=true

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY --from=prod-deps /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /opt/runtime-esbuild/ ./node_modules/
COPY --from=build /app/scripts/verifyRuntimeEnv.mjs ./scripts/verifyRuntimeEnv.mjs

EXPOSE 5000

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:' + (process.env.PORT || 5000) + '/api/health').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))"

CMD ["sh", "-c", "node scripts/verifyRuntimeEnv.mjs --mode ${RAGNAROK_RUNTIME_MODE:-alfa-testnet} --scope runtime && node dist/index.js --mode ${RAGNAROK_RUNTIME_MODE:-alfa-testnet}"]
