import type { CampaignChapter } from '../campaignTypes';
import { AI_PROFILES } from '../campaignTypes';

const x = (n: number) => 20000 + n;
const deck = (base: number) => Array.from({ length: 30 }, (_, j) => x(base + (j % 15)));

export const easternChapter: CampaignChapter = {
	id: 'eastern',
	name: 'The Celestial Gate: Myths Beyond the Veil',
	faction: 'eastern',
	description: 'Beyond the myths of the West lies an ancient truth. Chinese, Japanese, and Hindu gods await those who proved worthy across all four realms.',
	chapterReward: [{ type: 'pack', amount: 5 }, { type: 'rune', amount: 500 }],
	cinematicIntro: {
		title: 'The Celestial Gate: Myths Beyond the Veil',
		style: 'Ink-wash painting dissolves into golden temple architecture, cherry blossoms drift across transitions, jade and vermillion palette',
		scenes: [
			{
				narration: 'At the edge of the known mythologies stands a gate of jade and starlight. Beyond it lie heavens older than the Western gods can remember — celestial courts where bureaucrats manage the fate of billions, sacred mountains where enlightenment and annihilation are separated by a single breath.',
				visualCue: 'A towering gate materializes from mist, half torii arch, half Chinese paifang, decorated with Hindu mandalas. Stars wheel behind it. Cherry blossoms and lotus petals drift through the columns.',
				musicCue: 'Shakuhachi flute over a tampura drone, temple bells ring at intervals',
				durationHint: 15,
			},
			{
				narration: 'In the beginning, there was the cosmic egg — Pangu slept within it for eighteen thousand years. When he woke, he split it apart: the light half became the sky, the dark half became the earth. He held them apart until his body became the mountains, his blood the rivers, his breath the wind. From one sacrifice, a world was born.',
				visualCue: 'An enormous egg cracks open in darkness. A giant figure pushes sky from earth, growing larger as the gap widens. His body dissolves into landscapes — spine becoming mountain ranges, veins becoming rivers of jade.',
				musicCue: 'Deep taiko drums build from silence, erhu melody rises as the world forms',
				durationHint: 16,
			},
			{
				narration: 'But the heavens warred. Amaterasu hid in her cave and stole the sun. Susanoo raged across the ocean in exile. The Asuras and Devas churned the cosmic sea for immortality. Sun Wukong stormed the Jade Emperor\'s palace and ate the peaches of eternal life. Even paradise knows chaos.',
				visualCue: 'Split screen: a cave seals shut and darkness falls over Japan; a monkey in golden armor somersaults through a jade palace, scattering scrolls; gods and demons pull a serpent wrapped around a mountain as the ocean froths.',
				musicCue: 'Chaotic percussion — taiko, tabla, and gamelan clash together, then resolve into harmony',
				durationHint: 15,
			},
			{
				narration: 'And at the end of every age, Shiva opens his third eye and dances the Tandava — the dance that unmakes creation so it can be born anew. Destruction is not the end. It is the turning of the wheel. You have conquered the gods of the West. Now step through the Celestial Gate and face the myths that move the cosmos itself.',
				visualCue: 'A four-armed figure wreathed in fire dances inside a ring of flames. With each step, galaxies collapse and reform. The jade gate swings open, revealing an infinite staircase ascending into clouds lit by a thousand paper lanterns.',
				musicCue: 'Sitar and koto duet builds to a swell, then drops to reverent silence as the gate opens',
				durationHint: 15,
			},
		],
	},
	missions: [
		{
			id: 'eastern-1', chapterId: 'eastern', missionNumber: 1, realm: 'celestial_court',
			name: 'The Dragon Gate',
			description: 'A celestial dragon guards the threshold between worlds.',
			narrativeBefore: 'The waterfall roars where heaven meets earth. A carp that swims against the current to the top becomes a dragon — the Dragon Gate. But you are no carp. You are a conqueror of four mythologies, and the dragon that guards this gate knows it. It descends from the clouds, scales like liquid jade, eyes older than the mountains.',
			narrativeAfter: 'The dragon coils around the waterfall and bows its great head. "You have crossed the Dragon Gate," it rumbles. "Few from the Western myths have ever reached this far."',
			narrativeVictory: 'The dragon yields. The gate between worlds swings open.',
			narrativeDefeat: 'The waterfall crashes down. The Dragon Gate remains closed to you.',
			aiHeroId: 'hero-thorgrim', aiHeroClass: 'warrior',
			aiDeckCardIds: deck(0), aiProfile: AI_PROFILES.hard,
			bossRules: [{ type: 'extra_health', value: 10, description: 'The Dragon has 110 health' }],
			bossQuips: {
				onCombatStart: 'Few from the Western myths have ever swum the waterfall. Show me the muscle that brought you this far.',
				onLowHP: 'You have the patience of a carp. The patience that becomes dragon.',
				onLethal: 'Then I become the gate. Pass beneath my coils.',
				onVictory: 'The waterfall keeps its dragon. Try again next age.',
			},
			combatMusicId: 'celestial_court',
			victoryCinematic: [
				{ narration: 'The dragon coils around the waterfall and bows its great jade head. \u201cYou have crossed the Dragon Gate,\u201d it rumbles. \u201cFew from the Western myths have ever reached this far.\u201d', visualCue: 'A serpentine green dragon curling around a roaring waterfall, lowering its head a fraction.', musicId: 'celestial_court', durationHint: 12 },
			],
			defeatCinematic: [
				{ narration: 'The waterfall crashes down. The Dragon Gate remains closed to you.', musicId: 'celestial_court', durationHint: 7 },
			],
			storyBridge: [
				{ narration: 'A blinding light rises from the east. The Sun Goddess Amaterasu has heard you are here, and she is curious.', visualCue: 'A figure in white robes stepping out of a cave-mouth, light pouring around her.', musicId: 'celestial_court', durationHint: 8 },
			],
			prerequisiteIds: [],
			rewards: [{ type: 'rune', amount: 50 }],
			campaignArmy: { king: 'king-brimir', queen: 'hero-fujin', rook: 'hero-sarutahiko', bishop: 'hero-kamimusubi', knight: 'hero-tsukuyomi' },
		},
		{
			id: 'eastern-2', chapterId: 'eastern', missionNumber: 2, realm: 'takamagahara',
			name: 'Amaterasu\'s Dawn',
			description: 'The Japanese sun goddess emerges from her cave to judge the intruder.',
			narrativeBefore: 'The world has been dark since Amaterasu retreated into Ama-no-Iwato. The other gods danced and laughed to lure her out, and when she emerged, light returned to Japan. Now she turns that blinding radiance upon you. "You carry the shadows of Western gods," she says, her light burning away pretense. "Show me what remains when all shadow is stripped away."',
			narrativeAfter: 'Amaterasu dims her radiance to something bearable. "There is light in you that no shadow could hide," she says. "You may walk my lands."',
			narrativeVictory: 'You endure the purest light in existence. Amaterasu sees your true nature — and approves.',
			narrativeDefeat: 'The sun\'s full radiance unmakes every shadow you hid behind.',
			aiHeroId: 'hero-fujin', aiHeroClass: 'mage',
			aiDeckCardIds: deck(15), aiProfile: AI_PROFILES.amaterasu,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'Amaterasu has 110 health' },
				{ type: 'extra_mana', value: 1, description: 'Divine solar energy (+1 mana)' },
			],
			bossQuips: {
				onCombatStart: 'Once I retreated into the cave and the world went dark. I will not retreat from you. The world has had enough darkness.',
				onLowHP: 'There is light in you that no shadow could hide.',
				onLethal: 'Then take the dawn. The land of the rising sun is yours.',
				onVictory: 'Sleep, traveler. The shadows you carried have been burned away.',
			},
			combatMusicId: 'celestial_court',
			bossPhases: [
				{
					hpPercent: 50,
					quip: 'I am the SUN. There is no shadow you can stand in here.',
					flash: 'gold',
					effect: { type: 'damage_player', value: 7 },
					description: 'Amaterasu floods the field with light',
				},
			],
			victoryCinematic: [
				{ narration: 'Amaterasu dims her radiance to something a mortal can stand in. \u201cThere is light in you that no shadow could hide,\u201d she says. \u201cYou may walk my lands.\u201d', visualCue: 'A goddess in white robes lowering her hand. The world becomes liveable again.', musicId: 'celestial_court', durationHint: 11 },
			],
			defeatCinematic: [
				{ narration: 'The full radiance of the sun unmakes every shadow you ever hid behind. Including the ones that were keeping you upright.', musicId: 'twilight_horn', durationHint: 7 },
			],
			storyBridge: [
				{ narration: 'You walk on. The Jade Palace rises through the clouds, halls of pure jade stretching beyond mortal sight. The Jade Emperor is waiting with a celestial ledger and a stamp.', visualCue: 'A vast green palace floating among clouds, an emperor checking a scroll at a desk.', musicId: 'celestial_court', durationHint: 8 },
			],
			prerequisiteIds: ['eastern-1'],
			rewards: [{ type: 'rune', amount: 55 }],
			campaignArmy: { king: 'king-audumbla', queen: 'hero-sol', rook: 'hero-baldur', bishop: 'hero-kamimusubi', knight: 'hero-apollo' },
		},
		{
			id: 'eastern-3', chapterId: 'eastern', missionNumber: 3, realm: 'celestial_court',
			name: 'The Jade Emperor\'s Court',
			description: 'The ruler of Heaven in Chinese mythology holds court — and you are summoned.',
			narrativeBefore: 'The Jade Palace shimmers above the clouds, its halls of pure jade stretching beyond mortal sight. The Jade Emperor sits upon his throne, surrounded by celestial bureaucrats who manage every aspect of the mortal world. "You have defeated the gods of four lands," he says, checking a celestial ledger. "That is... irregular. We must rectify this."',
			narrativeAfter: 'The Jade Emperor stamps his celestial seal. "Irregular, but... acceptable," he says. "Your file has been updated. You may proceed."',
			narrativeVictory: 'Even heavenly bureaucracy bows to undeniable merit.',
			narrativeDefeat: 'The celestial bureaucracy finds you wanting. Your paperwork is denied.',
			aiHeroId: 'hero-hoenir', aiHeroClass: 'priest',
			aiDeckCardIds: deck(30), aiProfile: AI_PROFILES.jadeEmperor,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'The Jade Emperor has 110 health' },
				{ type: 'bonus_draw', value: 1, description: 'Celestial bureaucracy grants extra resources' },
			],
			bossQuips: {
				onCombatStart: 'You have defeated the gods of four lands. That is irregular. We must rectify this.',
				onLowHP: 'My ledger has no entry for what you are doing right now.',
				onLethal: 'Then I file you under \u201cexceptional cases.\u201d Stamp.',
				onVictory: 'Your case has been DENIED. Please try again in the next aeon.',
			},
			combatMusicId: 'celestial_court',
			bossPhases: [
				{
					hpPercent: 50,
					quip: 'CELESTIAL bureaucracy will deal with you in EVERY universe.',
					flash: 'gold',
					effect: { type: 'add_armor', value: 9 },
					description: 'The Jade Emperor calls in the entire celestial court',
				},
			],
			victoryCinematic: [
				{ narration: 'The Jade Emperor stamps his celestial seal. \u201cIrregular, but acceptable,\u201d he says. \u201cYour file has been updated. You may proceed.\u201d', visualCue: 'A jade-robed emperor stamping a scroll. A clerk filing it into a vast wall of identical scrolls.', musicId: 'celestial_court', durationHint: 11 },
			],
			defeatCinematic: [
				{ narration: 'The celestial bureaucracy finds you wanting. Your paperwork is denied in triplicate.', musicId: 'celestial_court', durationHint: 7 },
			],
			storyBridge: [
				{ narration: 'A storm gathers in the clouds outside the jade walls. Susanoo, banished from heaven for his destructiveness, has heard you are inside. He wants to test you.', visualCue: 'A storm-cloud roiling with a face. A long red beard inside the lightning.', musicId: 'jotun_rage', durationHint: 8 },
			],
			prerequisiteIds: ['eastern-2'],
			rewards: [{ type: 'rune', amount: 60 }],
			campaignArmy: { king: 'king-borr', queen: 'hero-odin', rook: 'hero-heimdall', bishop: 'hero-hera', knight: 'hero-hermes' },
		},
		{
			id: 'eastern-4', chapterId: 'eastern', missionNumber: 4, realm: 'takamagahara',
			name: 'Susanoo\'s Storm',
			description: 'The Japanese storm god unleashes typhoon fury.',
			narrativeBefore: 'Susanoo was banished from heaven for his destruction. He who slew the eight-headed serpent Yamata no Orochi now turns that storm-fury upon you. Rain slashes horizontally. Lightning strikes in sheets. The very ground dissolves into mud. "I was cast out of heaven!" he roars. "Do you think I fear anything?"',
			narrativeAfter: 'Susanoo\'s storm breaks. He stands in the rain, breathing heavily. "You\'re different from the Western gods I\'ve heard about," he says. "They rely on power. You rely on will."',
			narrativeVictory: 'The storm god\'s fury breaks against your resolve like waves on stone.',
			narrativeDefeat: 'No mortal can stand against the fury of heaven\'s exile.',
			aiHeroId: 'hero-ran', aiHeroClass: 'shaman',
			aiDeckCardIds: deck(45), aiProfile: AI_PROFILES.susanoo,
			bossRules: [
				{ type: 'extra_health', value: 10, description: 'Susanoo has 110 health' },
				{ type: 'passive_damage', value: 1, description: 'Typhoon deals 1 damage each turn' },
			],
			bossQuips: {
				onCombatStart: 'I was BANISHED from heaven. I slew the eight-headed Yamata no Orochi. Do you think I fear ANYTHING?',
				onLowHP: 'You\u2019re different from the Western gods. They rely on power. You rely on will.',
				onLethal: 'A storm settles, eventually. Even mine. Strike.',
				onVictory: 'Sleep in the rain. The world dissolves so easily.',
			},
			combatMusicId: 'jotun_rage',
			bossPhases: [
				{
					hpPercent: 50,
					quip: 'TYPHOON. Now. ALL of it.',
					flash: 'blue',
					effect: { type: 'damage_player', value: 8 },
					description: 'Susanoo unleashes the typhoon',
				},
			],
			victoryCinematic: [
				{ narration: 'Susanoo\u2019s storm breaks. He stands in the rain, breathing heavily, looking at you with new eyes. \u201cWill,\u201d he says. \u201cI had forgotten the word.\u201d', visualCue: 'A storm-god in the eye of his own quieting typhoon, looking at you with respect.', musicId: 'celestial_court', durationHint: 11 },
			],
			defeatCinematic: [
				{ narration: 'No mortal can stand against the fury of heaven\u2019s exile.', musicId: 'jotun_rage', durationHint: 7 },
			],
			storyBridge: [
				{ narration: 'A golden-furred figure somersaults down from a cloud. The Monkey King has heard about you. He wants to play.', visualCue: 'A grinning monkey with a gold staff bouncing into frame.', musicId: 'celestial_court', durationHint: 8 },
			],
			prerequisiteIds: ['eastern-3'],
			rewards: [{ type: 'rune', amount: 65 }, { type: 'eitr', amount: 100 }],
			campaignArmy: { king: 'king-surtr', queen: 'hero-fujin', rook: 'hero-thor', bishop: 'hero-poseidon', knight: 'hero-tsukuyomi' },
		},
		{
			id: 'eastern-5', chapterId: 'eastern', missionNumber: 5, realm: 'celestial_court',
			name: 'Monkey King\'s Challenge',
			description: 'Sun Wukong, the Monkey King, challenges you with impossible tricks.',
			narrativeBefore: 'A golden-furred figure somersaults down from a cloud, his Ruyi Jingu Bang staff extending to impossible lengths. Sun Wukong, the Monkey King — who fought the armies of heaven, who was trapped under a mountain for 500 years by the Buddha himself. He grins with monkey mischief. "I can transform 72 ways," he boasts. "I can fly 108,000 li in a single somersault. Beat that."',
			narrativeAfter: 'Sun Wukong scratches his head. "Huh. Not bad for someone who can\'t even somersault on clouds." He shrinks his staff to the size of a needle and tucks it behind his ear. "You\'re alright."',
			narrativeVictory: 'The irrepressible Monkey King is impressed. That alone is worth a legend.',
			narrativeDefeat: 'Sun Wukong laughs and does a backflip. "Too slow! Way too slow!"',
			aiHeroId: 'hero-gormr', aiHeroClass: 'rogue',
			aiDeckCardIds: deck(60), aiProfile: AI_PROFILES.sunWukong,
			bossRules: [
				{ type: 'extra_health', value: 15, description: 'Sun Wukong has 115 health' },
				{ type: 'bonus_draw', value: 1, description: '72 transformations grant extra cards' },
			],
			bossQuips: {
				onCombatStart: 'I can transform 72 ways. I can fly 108,000 li in a single somersault. The Buddha himself put me under a mountain. BEAT THAT.',
				onLowHP: 'Aw man. AW MAN. You\u2019re actually keeping up.',
				onLethal: 'Okay okay okay. You win this round. NEXT ONE\u2019s mine.',
				onVictory: 'Too slow! WAY too slow! Try eating peaches for a thousand years!',
			},
			combatMusicId: 'celestial_court',
			bossPhases: [
				{
					hpPercent: 50,
					quip: 'I HAVE seventy-two FORMS. I am about to use forty of them.',
					flash: 'gold',
					effect: { type: 'enrage', value: 10 },
					description: 'Sun Wukong cycles through transformations',
				},
			],
			victoryCinematic: [
				{ narration: 'Sun Wukong scratches his head. \u201cHuh. Not bad for someone who can\u2019t even somersault on clouds.\u201d He shrinks his Ruyi Jingu Bang to the size of a needle and tucks it behind his ear. \u201cYou\u2019re alright.\u201d', visualCue: 'A cocky monkey-king grinning, his enormous staff vanishing into a tiny needle.', musicId: 'celestial_court', durationHint: 11 },
			],
			defeatCinematic: [
				{ narration: 'Sun Wukong laughs and does a backflip. \u201cTOO SLOW! Way too slow!\u201d', musicId: 'celestial_court', durationHint: 7 },
			],
			storyBridge: [
				{ narration: 'You walk on. The next gate opens onto a darkness deeper than any underworld you have visited. Yomi. The mother of Japan is waiting.', visualCue: 'A pale woman in white burial robes, half her face beautiful, half her face the slow ruin of grief.', musicId: 'shadow_root', durationHint: 9 },
			],
			prerequisiteIds: ['eastern-4'],
			rewards: [{ type: 'rune', amount: 70 }],
			campaignArmy: { king: 'king-ginnungagap', queen: 'hero-loki', rook: 'hero-sarutahiko', bishop: 'hero-kamimusubi', knight: 'hero-loki' },
		},
		{
			id: 'eastern-6', chapterId: 'eastern', missionNumber: 6, realm: 'yomi',
			name: 'Izanami\'s Underworld',
			description: 'The mother of Japan waits in Yomi, the land of the dead.',
			narrativeBefore: 'Yomi is darker than any underworld you have visited. Izanami, mother of Japan, died giving birth to fire. Her husband Izanagi came to rescue her but fled when he saw her rotting form. She has not forgiven him — or any living thing — since. "You have visited many underworlds," she says. "This one will be your last."',
			narrativeAfter: 'Izanami retreats into the deepest dark. "Go," she whispers. "But remember: I kill a thousand living things each day in revenge. You are merely the one who got away."',
			narrativeVictory: 'You escape Yomi intact. Izanami\'s curse passes over you — this time.',
			narrativeDefeat: 'Yomi closes around you. Izanami collects another soul for her endless grief.',
			aiHeroId: 'hero-izanami', aiHeroClass: 'warlock',
			aiDeckCardIds: deck(75), aiProfile: AI_PROFILES.izanami,
			bossRules: [
				{ type: 'extra_health', value: 15, description: 'Izanami has 115 health' },
				{ type: 'passive_damage', value: 2, description: 'Yomi\'s decay deals 2 damage each turn' },
			],
			bossQuips: {
				onCombatStart: 'I died giving birth to fire. My husband fled when he saw what death had made of me. I have not forgiven any living thing since.',
				onLowHP: 'I kill a thousand living things each day in my grief. You will be one of them.',
				onLethal: 'Then leave Yomi. But know that I am still kneeling where you found me, and I am still grieving.',
				onVictory: 'Sleep beside me. The dead are kinder than the living, sometimes.',
			},
			combatMusicId: 'shadow_root',
			bossPhases: [
				{
					hpPercent: 50,
					quip: 'My grief HARDENS me. Look at it. LOOK at what death made of me.',
					flash: 'purple',
					effect: { type: 'add_armor', value: 12 },
					description: 'Izanami\u2019s grief becomes armor',
				},
			],
			victoryCinematic: [
				{ narration: 'Izanami retreats into the deepest dark. \u201cGo,\u201d she whispers. \u201cBut remember: I kill a thousand living things each day in revenge. You are merely the one who got away.\u201d', visualCue: 'A pale grieving figure stepping back into a sourceless dark, eyes still on you.', musicId: 'twilight_horn', durationHint: 11 },
			],
			defeatCinematic: [
				{ narration: 'Yomi closes around you. Izanami collects another soul for her endless grief.', musicId: 'shadow_root', durationHint: 7 },
			],
			storyBridge: [
				{ narration: 'A four-armed god with the head of an elephant is sitting cross-legged in the next chamber, smiling. He has a puzzle for you.', visualCue: 'A round elephant-headed god in saffron robes, four hands resting on his knees, eyes warm.', musicId: 'celestial_court', durationHint: 8 },
			],
			prerequisiteIds: ['eastern-5'],
			rewards: [{ type: 'rune', amount: 75 }, { type: 'card', cardId: 20021 }],
			campaignArmy: { king: 'king-tartarus', queen: 'hero-izanami', rook: 'hero-vidar', bishop: 'hero-ran', knight: 'hero-tsukuyomi' },
		},
		{
			id: 'eastern-7', chapterId: 'eastern', missionNumber: 7, realm: 'mount_meru',
			name: 'Ganesha\'s Puzzle',
			description: 'The elephant-headed god of wisdom presents an impossible riddle.',
			narrativeBefore: 'Ganesha sits cross-legged, his elephant head tilted thoughtfully. The Remover of Obstacles and the Placer of Obstacles — it depends on whether you are worthy. "I will set before you a puzzle," he says, holding up one of his four hands. "It cannot be solved by force, only by understanding. The Western gods rely on strength. Let us see if you have anything else."',
			narrativeAfter: 'Ganesha trumpets with joy. "Beautiful! You did not try to smash through it!" He hands you a golden tusk. "Carry this. It means you think before you strike."',
			narrativeVictory: 'Wisdom overcomes obstacles. Ganesha removes every barrier before you.',
			narrativeDefeat: 'Ganesha sighs. "You think like a warrior. Come back when you think like a sage."',
			aiHeroId: 'hero-frey', aiHeroClass: 'priest',
			aiDeckCardIds: deck(90), aiProfile: AI_PROFILES.ganesha,
			bossRules: [
				{ type: 'extra_health', value: 15, description: 'Ganesha has 115 health' },
				{ type: 'extra_mana', value: 2, description: 'Divine wisdom grants +2 mana' },
			],
			bossQuips: {
				onCombatStart: 'I am the Remover of Obstacles AND the Placer of Obstacles. It depends entirely on whether you are worthy. Show me.',
				onLowHP: 'You THINK before you strike. That is the rarest thing in any cosmos.',
				onLethal: 'A wise blow. Take the broken tusk, my friend. You will need it.',
				onVictory: 'You think like a warrior. Come back when you think like a sage.',
			},
			combatMusicId: 'celestial_court',
			bossPhases: [
				{
					hpPercent: 50,
					quip: 'I have FOUR hands and one of them is holding the puzzle.',
					flash: 'gold',
					effect: { type: 'heal_self', value: 12 },
					description: 'Ganesha solves the puzzle in his head while you fight',
				},
			],
			victoryCinematic: [
				{ narration: 'Ganesha trumpets with joy. \u201cBeautiful! You did not try to smash through it!\u201d He hands you a golden tusk. \u201cCarry this. It means you think before you strike.\u201d', visualCue: 'An elephant-headed god grinning, breaking off one tusk and offering it on his palm.', musicId: 'celestial_court', durationHint: 11 },
			],
			defeatCinematic: [
				{ narration: 'Ganesha sighs. \u201cYou think like a warrior. Come back when you think like a sage.\u201d', musicId: 'celestial_court', durationHint: 7 },
			],
			storyBridge: [
				{ narration: 'You walk on. The gods and demons are churning the cosmic ocean to make the elixir of immortality. They need a third party in the middle to keep things honest.', visualCue: 'A vast mountain spinning in a foaming sea, a colossal serpent wrapped around it as a churning rope.', musicId: 'celestial_court', durationHint: 9 },
			],
			prerequisiteIds: ['eastern-6'],
			rewards: [{ type: 'rune', amount: 80 }],
			campaignArmy: { king: 'king-yggdrasil', queen: 'hero-odin', rook: 'hero-sarutahiko', bishop: 'hero-kamimusubi', knight: 'hero-hermes' },
		},
		{
			id: 'eastern-8', chapterId: 'eastern', missionNumber: 8, realm: 'mount_meru',
			name: 'The Churning of the Ocean',
			description: 'Gods and demons churn the cosmic ocean to create the elixir of immortality.',
			narrativeBefore: 'Mount Mandara spins in the cosmic ocean, Vasuki the serpent king wrapped around it as a churning rope. The Devas pull one end, the Asuras the other. Vishnu himself takes the form of the turtle Kurma to support the mountain\u2019s weight on his shell. From the churning emerge wonders and terrors \u2014 the goddess Lakshmi rising on a lotus, the white horse Uchchaihshravas, the divine physician Dhanvantari carrying the Amrita vessel, celestial weapons, the sacred elephant Airavata. But before the nectar comes the poison. Halahala \u2014 a venom so deadly it would destroy all creation \u2014 bubbles up from the ocean floor. The gods and demons alike recoil. Only Shiva steps forward. He takes the poison into his mouth and holds it in his throat, which turns blue-black forever. Parvati grips his throat to prevent him from swallowing, saving his life but staining him the color of midnight. The churning continues. The Amrita is close. Both sides want it. You stand in the middle of a cosmic tug-of-war.',
			narrativeAfter: 'The churning stops. The Amrita glows in its vessel, and you have earned a single sip. Immortality touches your lips — not forever, but long enough to face what comes next.',
			narrativeVictory: 'You stand between gods and demons and claim the Amrita. Both sides are impressed.',
			narrativeDefeat: 'The cosmic ocean swallows you. The churning continues without you.',
			aiHeroId: 'hero-gefjon', aiHeroClass: 'shaman',
			aiDeckCardIds: deck(105), aiProfile: AI_PROFILES.boss,
			bossRules: [
				{ type: 'extra_health', value: 15, description: 'Cosmic forces have 115 health' },
				{ type: 'extra_mana', value: 2, description: 'Cosmic energy grants +2 mana' },
				{ type: 'bonus_draw', value: 1, description: 'The churning produces extra resources' },
			],
			bossQuips: {
				onCombatStart: 'Pull, gods! Pull, demons! Vasuki holds the line! The Amrita is so close.',
				onLowHP: 'Even the cosmic ocean has a bottom. We are nearly there.',
				onLethal: 'Then take the cup. The first sip is yours.',
				onVictory: 'Both sides drink. Both sides become immortal. Tomorrow they fight again.',
			},
			combatMusicId: 'celestial_court',
			bossPhases: [
				{
					hpPercent: 60,
					quip: 'POISON rises before the elixir. Drink it, Shiva! Save us!',
					flash: 'green',
					effect: { type: 'damage_player', value: 8 },
					description: 'The poison Halahala rises from the churning',
				},
				{
					hpPercent: 30,
					quip: 'AMRITA. The nectar. NOW.',
					flash: 'gold',
					effect: { type: 'enrage', value: 11 },
					description: 'The Amrita rises from the cosmic ocean',
				},
			],
			victoryCinematic: [
				{ narration: 'The churning stops. The Amrita glows in its vessel, and you have earned a single sip. Immortality touches your lips \u2014 not forever, but long enough to face what comes next.', visualCue: 'A golden cup at the center of a calming sea. A single drop of light meeting your lips.', musicId: 'celestial_court', durationHint: 12 },
			],
			defeatCinematic: [
				{ narration: 'The cosmic ocean swallows you. The churning continues without you, indifferent.', musicId: 'shadow_root', durationHint: 7 },
			],
			storyBridge: [
				{ narration: 'A figure dances in the next chamber. Each step destroys a universe. Each spin creates a new one. She is black as the void between stars, wearing a garland of skulls. Time itself, with a tongue red with the blood of demons, looking right at you.', visualCue: 'A goddess in mid-dance, multiple arms in motion, a necklace of skulls swinging.', musicId: 'shadow_root', durationHint: 9 },
			],
			prerequisiteIds: ['eastern-7'],
			rewards: [{ type: 'rune', amount: 85 }, { type: 'eitr', amount: 150 }],
			campaignArmy: { king: 'king-brimir', queen: 'hero-fujin', rook: 'hero-thor', bishop: 'hero-poseidon', knight: 'hero-tsukuyomi' },
		},
		{
			id: 'eastern-9', chapterId: 'eastern', missionNumber: 9, realm: 'diyu',
			name: 'Kali\'s Dance of Destruction',
			description: 'The Hindu goddess of time and death dances the world toward its end.',
			narrativeBefore: 'Kali dances the Tandava \u2014 Shiva\u2019s own dance of annihilation, performed by his fiercest aspect. She is Devi in her most terrible form: black as the void between stars, four arms whirling, wearing a garland of fifty-two skulls \u2014 one for each letter of the Sanskrit alphabet, because she is the destruction of language itself. Her tongue lolls red with the blood of the demon Raktabija, whose every drop of spilled blood spawned a new demon until Kali drank it all. Each step destroys a universe. Each spin creates a new one. She is not evil \u2014 she is liberation. In Hindu philosophy, Kali is moksha: the annihilation of the ego, the stripping of illusion, the terrifying freedom of seeing reality without the comfort of lies. The garland is not trophies; it is the alphabet being returned to silence. "Dance with me," she says, her wild eyes burning. "If you can keep up, you will see what lies behind the world. If not..." She laughs, and galaxies tremble.',
			narrativeAfter: 'Kali stops dancing. The silence is deafening. "You... kept up," she says, genuinely surprised. "No one has ever kept up." She removes one skull from her necklace. "Take this. It belonged to a god who thought he was stronger than Time. You are wiser."',
			narrativeVictory: 'You dance with destruction itself and survive. Kali keeps time — and you kept pace.',
			narrativeDefeat: 'Time dances on. You do not.',
			aiHeroId: 'hero-dionysus', aiHeroClass: 'warlock',
			aiDeckCardIds: deck(120), aiProfile: AI_PROFILES.kali,
			bossRules: [
				{ type: 'extra_health', value: 20, description: 'Kali has 120 health' },
				{ type: 'extra_mana', value: 2, description: 'Time\'s power grants +2 mana' },
				{ type: 'passive_damage', value: 2, description: 'Kali\'s dance deals 2 damage each turn' },
			],
			bossQuips: {
				onCombatStart: 'Dance with me. Each step destroys a universe. Each spin creates a new one. KEEP UP or be left behind.',
				onLowHP: 'You. KEEP. UP. Nobody keeps up with the dance of time.',
				onLethal: 'Then take this skull. It belonged to a god who thought he was stronger than time. You are wiser.',
				onVictory: 'Time dances on. You do not.',
			},
			combatMusicId: 'shadow_root',
			bossPhases: [
				{
					hpPercent: 65,
					quip: 'My garland of skulls grows by one head each step. KEEP COUNT.',
					flash: 'red',
					effect: { type: 'damage_player', value: 9 },
					description: 'Kali\u2019s dance accelerates',
				},
				{
					hpPercent: 30,
					quip: 'I am TIME. Time always wins.',
					flash: 'purple',
					effect: { type: 'enrage', value: 13 },
					description: 'Kali enters the destruction phase',
				},
			],
			victoryCinematic: [
				{ narration: 'Kali stops dancing. The silence is deafening. \u201cYou kept up,\u201d she says, genuinely surprised. \u201cNo one has ever kept up.\u201d She removes one skull from her necklace and offers it to you.', visualCue: 'A many-armed dancing goddess going still in mid-step. A skull lifted from a long necklace and held out.', musicId: 'celestial_court', durationHint: 12 },
			],
			defeatCinematic: [
				{ narration: 'Time dances on. You do not.', musicId: 'twilight_horn', durationHint: 7 },
			],
			storyBridge: [
				{ narration: 'And then the barriers between mythologies begin to crack. Norse, Greek, Egyptian, Celtic, Eastern \u2014 every pantheon\u2019s apocalypse is converging on a single point at the same instant. The final battle is about to begin.', visualCue: 'A black point in the sky widening into a portal. Every mythology\u2019s end-time symbol pouring out at once.', musicId: 'ragnarok', durationHint: 12 },
			],
			prerequisiteIds: ['eastern-8'],
			rewards: [{ type: 'rune', amount: 90 }, { type: 'card', cardId: 20114 }],
			campaignArmy: { king: 'king-ginnungagap', queen: 'hero-izanami', rook: 'hero-logi', bishop: 'hero-ran', knight: 'hero-nyx' },
		},
		{
			id: 'eastern-10', chapterId: 'eastern', missionNumber: 10, realm: 'celestial_court',
			name: 'Ragnarok of All Worlds',
			description: 'Every mythology collides. The final battle for all creation.',
			narrativeBefore: 'The barriers between mythologies shatter. Norse, Greek, Egyptian, Celtic, Chinese, Japanese, Hindu — every pantheon\'s apocalypse arrives simultaneously. Ragnarok. Gigantomachy. The devouring of Ra. The final Fomorian war. The celestial collapse. They all happen at once, in the same place, and at the center of it all stands the adversary: a being woven from every mythology\'s concept of the End. "You conquered each pantheon separately," it speaks with a thousand voices. "Now face them all at once."',
			narrativeAfter: 'Silence. For the first time in the history of every mythology, the End was met — and turned back. The being of endings unravels, and from its dissolution, new stories begin. You stand at the nexus of all myths, the one who prevented the final Ragnarok. Every god, from every pantheon, knows your name. The campaign is complete.',
			narrativeVictory: 'You are the champion of all mythologies. The one who stood at the end of everything and said: "Not today." Every god across every pantheon bows.',
			narrativeDefeat: 'All endings arrive at once. But even this is just a story — and stories can be retold.',
			aiHeroId: 'hero-hyperion', aiHeroClass: 'mage',
			aiDeckCardIds: deck(135), aiProfile: AI_PROFILES.boss,
			bossRules: [
				{ type: 'extra_health', value: 30, description: 'The World-Ender has 130 health' },
				{ type: 'extra_mana', value: 3, description: 'All mythologies\' power combined (+3 mana)' },
				{ type: 'bonus_draw', value: 2, description: 'Draws from every pantheon\'s arsenal' },
				{ type: 'passive_damage', value: 2, description: 'The unraveling deals 2 damage each turn' },
			],
			bossQuips: {
				onCombatStart: 'You conquered each pantheon SEPARATELY. Now face them ALL AT ONCE. I am every ending. I am Ragnarok. I am Gigantomachy. I am the Devouring of Ra. I am the Final Fomorian War. I am the Celestial Collapse. And I have been waiting for you.',
				onLowHP: 'You stand against EVERY ending. No mortal has even imagined this.',
				onLethal: 'Then strike. The endings will simply find another door.',
				onVictory: 'All endings. All AT ONCE. The story finishes the only way every story finishes.',
			},
			combatMusicId: 'ragnarok',
			bossPhases: [
				{
					hpPercent: 85,
					quip: 'I am NORSE Ragnarok. The wolf. The serpent. The fire-giant. ALL of it.',
					flash: 'red',
					effect: { type: 'damage_player', value: 12 },
					description: 'The Norse end-times manifest',
				},
				{
					hpPercent: 70,
					quip: 'I am GREEK Gigantomachy. The Giants. Typhon. Gaia\u2019s tired final breath.',
					flash: 'gold',
					effect: { type: 'damage_player', value: 12 },
					description: 'The Greek end-times manifest',
				},
				{
					hpPercent: 55,
					quip: 'I am EGYPTIAN apocalypse. The Sun barge swallowed by Apophis. The dawn that does not come.',
					flash: 'red',
					effect: { type: 'add_armor', value: 16 },
					description: 'The Egyptian end-times manifest',
				},
				{
					hpPercent: 35,
					quip: 'I am CELTIC ending. The Otherworld closes its mists for the last time. The Tuatha go into the mounds and never come out.',
					flash: 'green',
					effect: { type: 'heal_self', value: 18 },
					description: 'The Celtic end-times manifest',
				},
				{
					hpPercent: 15,
					quip: 'And I am EASTERN finality. Kali\u2019s last dance. The dragon swallows its tail. THE COSMOS BREATHES OUT.',
					flash: 'purple',
					effect: { type: 'enrage', value: 18 },
					description: 'All endings simultaneous',
				},
			],
			victoryCinematic: [
				{ narration: 'Silence. For the first time in the history of any mythology, the End was met \u2014 and turned BACK.', visualCue: 'A cosmic shape unraveling into starlight. Every mythology\u2019s end-time symbol going dim.', musicId: 'rebirth', durationHint: 14 },
				{ narration: 'From its dissolution, new stories begin. You stand at the nexus of all myths, the one who prevented the final Ragnarok. Every god, from every pantheon, knows your name.', visualCue: 'A great pale circle of gods from every pantheon \u2014 Norse, Greek, Egyptian, Celtic, Hindu, Japanese, Chinese \u2014 all turning to look at you in silence.', musicId: 'rebirth', durationHint: 16 },
				{ narration: 'Odin nods. Zeus inclines his head. Ra raises a hand in salute. Lugh lowers his spear. The Jade Emperor stamps a single seal on the only ledger that ever mattered. Vidar, in the back, gives the smallest possible smile.', visualCue: 'Each god named in turn, in close-up, acknowledging the player.', musicId: 'rebirth', durationHint: 16 },
				{ narration: 'You are the champion of all mythologies. The one who stood at the end of everything and said: \u201cNot today.\u201d', visualCue: 'A single figure on a green hill at sunrise, every pantheon\u2019s symbol fading like stars at dawn around them.', musicId: 'rebirth', durationHint: 14 },
				{ narration: 'Rest now, hero of every world. The next saga is for the children. You wrote the one that ended the endings.', musicId: 'rebirth', durationHint: 12 },
			],
			defeatCinematic: [
				{ narration: 'All endings arrive at once. Ragnarok and Gigantomachy and the devouring of Ra and the closing of the mounds and the last dance of Kali, simultaneous, total. Every mythology finishes itself in a single breath.', visualCue: 'Five different apocalypses superimposed in slow motion. A single quiet note holding them together.', musicId: 'ragnarok', durationHint: 12 },
				{ narration: 'But even this is just a story. And stories can be retold.', musicId: 'rebirth', durationHint: 8 },
			],
			prerequisiteIds: ['eastern-9'],
			rewards: [{ type: 'rune', amount: 200 }, { type: 'card', cardId: 20001 }, { type: 'pack', amount: 5 }],
			campaignArmy: { king: 'king-ginnungagap', queen: 'hero-zeus', rook: 'hero-thor', bishop: 'hero-poseidon', knight: 'hero-loki' },
			starThresholds: { threeStar: 20, twoStar: 30 },
			isChapterFinale: true,
		},
	],
};
