import {
	resolveRagnarokRuntimeConfig,
	type RagnarokRuntimeConfig,
	type RagnarokRuntimeEnv,
} from '../../shared/runtimeConfig';

function getServerRuntimeEnv(): RagnarokRuntimeEnv {
	return {
		VITE_NETWORK_STAGE: process.env.VITE_NETWORK_STAGE,
		VITE_RAGNAROK_PROTOCOL_ID: process.env.VITE_RAGNAROK_PROTOCOL_ID,
		VITE_RAGNAROK_COLLECTION_ID: process.env.VITE_RAGNAROK_COLLECTION_ID,
		VITE_RAGNAROK_ADMIN_ACCOUNT: process.env.VITE_RAGNAROK_ADMIN_ACCOUNT,
		VITE_RAGNAROK_ADMIN_OPERATOR_ACCOUNT: process.env.VITE_RAGNAROK_ADMIN_OPERATOR_ACCOUNT,
		VITE_RAGNAROK_GENESIS_ACCOUNT: process.env.VITE_RAGNAROK_GENESIS_ACCOUNT,
		VITE_RAGNAROK_TREASURY_ACCOUNT: process.env.VITE_RAGNAROK_TREASURY_ACCOUNT,
		VITE_RAGNAROK_INDEX_ACCOUNT: process.env.VITE_RAGNAROK_INDEX_ACCOUNT,
		VITE_RAGNAROK_INDEXER_URL: process.env.VITE_RAGNAROK_INDEXER_URL,
		VITE_RAGNAROK_ART_INDEXER_URL: process.env.VITE_RAGNAROK_ART_INDEXER_URL,
		VITE_NFTLOX_PROTOCOL_ID: process.env.VITE_NFTLOX_PROTOCOL_ID,
		VITE_NFT_ART_BASE_URL: process.env.VITE_NFT_ART_BASE_URL,
		VITE_EXTERNAL_URL_BASE: process.env.VITE_EXTERNAL_URL_BASE,
		VITE_RAGNAROK_RESET_EPOCH: process.env.VITE_RAGNAROK_RESET_EPOCH,
		VITE_SEASON_START: process.env.VITE_SEASON_START,
		RAGNAROK_PROTOCOL_ID: process.env.RAGNAROK_PROTOCOL_ID,
		RAGNAROK_RESET_EPOCH: process.env.RAGNAROK_RESET_EPOCH,
		RAGNAROK_ADMIN_OPERATOR_ACCOUNT: process.env.RAGNAROK_ADMIN_OPERATOR_ACCOUNT,
		RAGNAROK_SEASON_START: process.env.RAGNAROK_SEASON_START,
		RAGNAROK_NFTLOX_COLLECTION_PROOF: process.env.RAGNAROK_NFTLOX_COLLECTION_PROOF,
		RAGNAROK_HIVE_KEYCHAIN_SMOKE: process.env.RAGNAROK_HIVE_KEYCHAIN_SMOKE,
		RAGNAROK_P2P_TWO_BROWSER_SMOKE: process.env.RAGNAROK_P2P_TWO_BROWSER_SMOKE,
		RAGNAROK_CLOSED_BETA_OPERATOR_SIGNOFF: process.env.RAGNAROK_CLOSED_BETA_OPERATOR_SIGNOFF,
	};
}

export function getRagnarokServerRuntimeConfig(): RagnarokRuntimeConfig {
	return Object.freeze(resolveRagnarokRuntimeConfig(getServerRuntimeEnv()));
}
